[server]
address = "127.0.0.1"
maxUploadSize = 10

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6FA"
textColor = "#183B56"
font = "sans serif"
